# Tensorflow2.0 小练习


In [1]:
import tensorflow as tf
import numpy as np

2025-03-23 17:44:08.858755: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-23 17:44:08.879499: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1742723048.903922  793897 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742723048.911606  793897 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-23 17:44:08.947078: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

## 实现 softmax 函数


In [3]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    prob_x = tf.exp(x) / tf.reduce_sum(tf.exp(x), axis=-1, keepdims=True)
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

I0000 00:00:1742723124.184871  793897 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 73651 MB memory:  -> device: 0, name: NVIDIA A800 80GB PCIe, pci bus id: 0000:4f:00.0, compute capability: 8.0
I0000 00:00:1742723124.186490  793897 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 79069 MB memory:  -> device: 1, name: NVIDIA A800 80GB PCIe, pci bus id: 0000:52:00.0, compute capability: 8.0
I0000 00:00:1742723124.187661  793897 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 79069 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:56:00.0, compute capability: 8.0
I0000 00:00:1742723124.197133  793897 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 79069 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:57:00.0, compute capability: 8.0
I0000 00:00:1742723124.203825  793897 gpu_device.cc:2022] Create

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 sigmoid 函数


In [4]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    prob_x = 1 / (1 + tf.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵 loss 函数


In [13]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss = -tf.reduce_sum(label * tf.math.log(x), axis=-1)
    
    return tf.reduce_mean(loss)

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵 loss 函数


In [29]:
def sigmoid_ce(x, label):
    ##########
    '''实现 sigmoid 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss = label * (-tf.math.log(x)) + (1 - label) * (-tf.math.log(1 - x))
    return tf.reduce_mean(loss)

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 0. 0. 0. 1. 0. 1. 0. 0. 0.]


True